### ISSUE TITLE
Support Laravel 10 & PHP 8.1

### ISSUE THREAD

**Issue by heikokrebs** [fourstacks/flexible-presenter#39]
Hey,
love this package. Is it possible to tag release for Laravel 10 with PHP 8.1 support?

**Comment by fourstacks** [comment]
Yep!  I'm planning on upgrading a project using it to L10 this week so I'll work on this pretty soon and tag a release

**Comment by heikokrebs** [comment]
@fourstacks Thanks for the fast reply! Sounds great 🙃

**Comment by fourstacks** [comment]
@heikokrebs - just tagged a new version (`4.x`) which has support for Laravel 10.  Shout if you run into any issues 👍

**Comment by heikokrebs** [comment]
Thanks a lot for your work @fourstacks!
